services:
  - type: web
    name: traderz-vip-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "itt-a-tokened"
